wechat:
  app_id: wx74374b7595b9a02a
  app_secret: 5f958e827386540544e4b9a812074f65
  app_timeout: 600
web:
  upPath: D:/file/     #//自定义属性,以/结尾
  upUrl: /file/**
server:
  port: ${port:9090}
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
      url: jdbc:mysql://192.168.1.92:3306/hnzrwl?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
        max-active: 0                           #最大连接数量
        max-idle: 0                             #最大空闲连接数量
        initial-size: 10                        #初始化连接数量
        min-idle: 10                            #最小空闲连接数量
        defaultAutoCommit: false                #是否自动提交。通常需设置为false
        validation-query: select 1              #用于验证数据库连接是否可用的SQL语句
        testWhileIdle: true                     #是否测试空闲的数据库连接
        timeBetweenEvictionRunsMillis: 5000     #检查连接是否可用的间隔时间。单位毫秒。默认5秒
        minEvictableIdleTimeMillis: 6000        #连接最少保存时间。单位毫秒。默认60秒
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8